# Generated by Django 4.0 on 2021-12-29 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player/', verbose_name='photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='player')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'Player',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='question')),
                ('response', models.CharField(max_length=250, verbose_name='response')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='image')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='audio')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='video')),
                ('propositionOne', models.CharField(blank=True, max_length=250, null=True, verbose_name='propositionOne')),
                ('propositionTwo', models.CharField(blank=True, max_length=250, null=True, verbose_name='propositionTwo')),
                ('propositionThree', models.CharField(blank=True, max_length=250, null=True, verbose_name='propositionThree')),
                ('propositionFour', models.CharField(blank=True, max_length=250, null=True, verbose_name='propositionFour')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'Question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='score')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player', verbose_name='players')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'db_table': 'score',
                'managed': True,
            },
        ),
    ]
