# Generated by Django 4.0 on 2021-12-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/player/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='static/audio/', verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/video/', verbose_name='video'),
        ),
    ]
