# Generated by Django 4.0 on 2021-12-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_player_photo_alter_question_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='activate',
            field=models.BooleanField(default=False, verbose_name='activate'),
        ),
    ]
