# Generated by Django 4.0 on 2021-12-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='activate'),
        ),
    ]
