# Generated by Django 4.0 on 2021-12-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_question_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50, verbose_name='room')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'last_question',
                'verbose_name_plural': 'last_questions',
                'db_table': 'last_question',
                'managed': True,
            },
        ),
    ]
