# Generated by Django 4.0 on 2021-12-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_last_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last_question',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.question', verbose_name='question'),
        ),
    ]
