# Generated by Django 4.0 on 2021-12-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_categorie_question_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='nameId',
            field=models.CharField(default=1, max_length=250, verbose_name='nameId'),
            preserve_default=False,
        ),
    ]
