# Generated by Django 4.0 on 2021-12-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_categorie_nameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='activate'),
        ),
    ]
