# Generated by Django 4.0 on 2021-12-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_categorie_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=0, verbose_name='number'),
        ),
    ]
